### PR TITLE
readme, authors and history files added to project

### PR DESCRIPTION
**Pull request by ClaireMath**

### CODE REVIEW

**Review by an-ham — COMMENTED** [review]
Don't forget to add all the metrics to the arraylist so that we get all the logs.
Thank you.

**Comment by ClaireMath** [comment]
Ok thanks, I'm going to change it right away !

**Comment by ClaireMath** [comment]
oupsy, I 've created a new commit for your last comment, instead of amending the last one. so you'll receive a new pull request very soon for the arraylist completion.

**Comment by an-ham** [comment]
Ok !

**Pull request merged**
